# Nixpacks configuration for Railway
# This file is optional but can help with build optimization

[phases.setup]
nixPkgs = ["python311", "python311Packages.venv", "gcc", "libffi", "openssl"]

[phases.install]
cmds = [
    "python -m venv venv",
    "venv/bin/python -m pip install --upgrade pip",
    "venv/bin/python -m pip install -r requirements.txt"
]

[start]
cmd = "venv/bin/python bot_hwb.py"

[variables]
PYTHONUNBUFFERED = "1"
