# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl", "libxml2", "libxslt"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --target ./libs -r requirements.txt"
]

[variables]
PYTHONUNBUFFERED = "1"
