# Nixpacks configuration for Railway
# This file is optional but can help with build optimization

[phases.setup]
nixPkgs = ["python311", "curl", "gcc", "libffi", "openssl"]

[phases.install]
cmds = [
    "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python get-pip.py",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python bot_hwb.py"

[variables]
PYTHONUNBUFFERED = "1"
