# Nixpacks configuration for Railway
# This file is optional but can help with build optimization

[phases.setup]
nixPkgs = ["python311Full", "gcc", "libffi", "openssl"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python bot_hwb.py"

[variables]
PYTHONUNBUFFERED = "1"
